In [1]:
import numpy as np

In [2]:
# Vendas diárias de uma loja (em R$) ao longo de 10 dias
vendas = np.array([1200, 1350, 980, 1500, 1100, 
                    1650, 1400, 1250, 1800, 1300])

print(vendas)
print(f"Tipo: {vendas.dtype}, Formato: {vendas.shape}")

[1200 1350  980 1500 1100 1650 1400 1250 1800 1300]
Tipo: int64, Formato: (10,)


In [3]:
print(f"Total vendido: R$ {vendas.sum()}")
print(f"Média diária: R$ {vendas.mean():.2f}")
print(f"Maior venda: R$ {vendas.max()} (dia {vendas.argmax() + 1})")
print(f"Menor venda: R$ {vendas.min()} (dia {vendas.argmin() + 1})")
print(f"Desvio padrão: R$ {vendas.std():.2f}")

Total vendido: R$ 13530
Média diária: R$ 1353.00
Maior venda: R$ 1800 (dia 9)
Menor venda: R$ 980 (dia 3)
Desvio padrão: R$ 234.91


In [11]:
soma = 0
maxValue = 0
minValue = vendas[0]
for i in vendas:
    print(i)
    soma += i
    if i > maxValue:
        maxValue = i
    if i < minValue:
        minValue = i
mean = soma/len(vendas)
print(f"soma: {soma}")
print(f"media {mean}")
print(f"Maior {maxValue}")
print(f"Menor {minValue}")




1200
1350
980
1500
1100
1650
1400
1250
1800
1300
soma: 13530
media 1353.0
Maior 1800
Menor 980


In [12]:
# Linhas = produtos, Colunas = dias
vendas_produtos = np.array([
    [120, 135, 98, 150, 110],   # Produto A
    [200, 210, 195, 220, 205],  # Produto B
    [80,  90,  75,  85,  95]    # Produto C
])

print(vendas_produtos.shape)  # (3, 5) -> 3 produtos, 5 dias

(3, 5)


In [ ]:
# axis=0 -> desce as colunas (soma por dia, todos produtos)
total_por_dia = vendas_produtos.sum(axis=0)
print("Total por dia:", total_por_dia)

# axis=1 -> percorre as linhas (soma por produto, todos os dias)
total_por_produto = vendas_produtos.sum(axis=1)
print("Total por produto:", total_por_produto)

In [13]:
# Quais dias o produto A vendeu mais de 100 unidades?
produto_a = vendas_produtos[0]
dias_bons = produto_a[produto_a > 100]
print("Vendas acima de 100:", dias_bons)

# Quantos dias isso aconteceu?
print("Quantidade de dias:", (produto_a > 100).sum())

Vendas acima de 100: [120 135 150 110]
Quantidade de dias: 4


In [18]:
# Aplicar um aumento de 10% em todas as vendas
vendas_com_reajuste = vendas_produtos * 1.10
print(vendas_com_reajuste)

# Comparar dois produtos, elemento por elemento
diferenca = vendas_produtos[1] - vendas_produtos[0]  # B menos A
print("Diferença B-A por dia:", diferenca)

[[132.  148.5 107.8 165.  121. ]
 [220.  231.  214.5 242.  225.5]
 [ 88.   99.   82.5  93.5 104.5]]
Diferença B-A por dia: [80 75 97 70 95]


In [15]:
# Padronização: (valor - média) / desvio padrão
vendas_normalizadas = (vendas - vendas.mean()) / vendas.std()
print(vendas_normalizadas)

[-0.65132335 -0.01277105 -1.58786673  0.62578126 -1.07702488  1.26433356
  0.20007972 -0.43847258  1.90288586 -0.22562181]


In [16]:
# Dataset: notas de alunos em 4 provas
notas = np.array([
    [7.5, 8.0, 6.5, 9.0],
    [5.5, 6.0, 7.0, 5.0],
    [9.0, 8.5, 9.5, 8.0],
    [4.0, 5.5, 6.0, 5.5]
])

media_por_aluno = notas.mean(axis=1)
print("Média por aluno:", media_por_aluno)

aprovados = media_por_aluno >= 6.0
print("Aprovados (True/False):", aprovados)
print("Quantidade de aprovados:", aprovados.sum())

melhor_aluno = media_por_aluno.argmax()
print(f"Melhor aluno: índice {melhor_aluno}, média {media_por_aluno[melhor_aluno]:.2f}")

Média por aluno: [7.75  5.875 8.75  5.25 ]
Aprovados (True/False): [ True False  True False]
Quantidade de aprovados: 2
Melhor aluno: índice 2, média 8.75
