In [2]:
import numpy as np

In [2]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)
c_signed32 = a - b.astype(np.int32)
print('signed c:', c_signed32, c_signed32.dtype)

unsigned c: [4294967293 4294967293 4294967293] uint32
signed c: [-3 -3 -3] int64


linspace cria arrays començando no primeiro parametro, terminando no segundo, com a quantidade do terceiro e divididos na mesma proporção

In [8]:
np.linspace(1., 4., 3)

array([1. , 2.5, 4. ])

In [ ]:
eye cria matrizes, se um parametro quadradas como numero 1 na diagonal principal ou com o dois declarando o numero de elmentos desejado

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(4,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [ ]:
ja usando o dialog, pode se definir valores para as diagonais

In [3]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
apartir da celula 1

In [ ]:
np.diag([1, 2, 3],1)