In [1]:
import numpy as np

In [4]:
np.linspace(5., 20., 3)

array([ 5. , 12.5, 20. ])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
vendas = np.array([1200, 1350, 980, 1500, 1100, 
                    1650, 1400, 1250, 1800, 1300])

print(vendas)
print(f"Tipo: {vendas.dtype}, Formato: {vendas.shape}")

[1200 1350  980 1500 1100 1650 1400 1250 1800 1300]
Tipo: int64, Formato: (10,)


In [8]:
vendas2 = [15, 52, 35, 25]

In [9]:
print(vendas2)

[15, 52, 35, 25]


In [23]:
soma = 0
maxValue = 0
minValue = vendas[0]
for i in vendas:
    soma+= i
    if i > maxValue:
        maxValue = i
        print(f"max= {maxValue}")
    if i < minValue:
        minValue = i
        print(f"min= {minValue}")
media = soma / len(vendas)
print(f"soma: {soma}")
print(f"media {media}")
print(f"Maior {maxValue}")
print(f"Menor {minValue}")

max= 1200
max= 1350
min= 980
max= 1500
max= 1650
max= 1800
soma: 13530
media 1353.0
Maior 1800
Menor 980


In [24]:
print(f"Total vendido: R$ {vendas.sum()}")


Total vendido: R$ 13530


In [19]:
media = soma / len(vendas)
print(f"media: {media}")

media: 1353.0


In [20]:
print(f"Média diária: R$ {vendas.mean():.2f}")


Média diária: R$ 1353.00


In [25]:
print(f"Total vendido: R$ {vendas.sum()}")
print(f"Média diária: R$ {vendas.mean():.2f}")
print(f"Maior venda: R$ {vendas.max()} (dia {vendas.argmax() + 1})")
print(f"Menor venda: R$ {vendas.min()} (dia {vendas.argmin() + 1})")

Total vendido: R$ 13530
Média diária: R$ 1353.00
Maior venda: R$ 1800 (dia 9)
Menor venda: R$ 980 (dia 3)


In [27]:
vendas_produtos = np.array([
    [120, 135, 98, 150, 110],   # Produto A
    [200, 210, 195, 220, 205],  # Produto B
    [80,  90,  75,  85,  95]    # Produto C
])

In [32]:
print(vendas_produtos.shape)

(3, 5)


In [33]:
total_por_dia = vendas_produtos.sum(axis=0)
print(f"Total por dia: {total_por_dia}")

Total por dia: [400 435 368 455 410]


In [34]:
total_por_produto = vendas_produtos.sum(axis=1)
print(f"Total por produto: {total_por_produto}")

Total por produto: [ 613 1030  425]


In [36]:
vendas_com_reajuste = vendas_produtos * 1.10

In [37]:
print(vendas_com_reajuste)

[[132.  148.5 107.8 165.  121. ]
 [220.  231.  214.5 242.  225.5]
 [ 88.   99.   82.5  93.5 104.5]]


In [38]:
diferenca = vendas_produtos[1] - vendas_produtos[0]  # B menos A
print("Diferença B-A por dia:", diferenca)

Diferença B-A por dia: [80 75 97 70 95]


In [39]:
diferencaItem = vendas_produtos[1][0] - vendas_produtos[0][0] # B menos A
print("Diferença Item 0 B-A por dia:", diferencaItem)

Diferença Item 0 B-A por dia: 80


In [41]:
vendas_normalizadas = (vendas_produtos - vendas_produtos.mean()) / vendas_produtos.std()
print(vendas_normalizadas)

[[-0.34322719 -0.05507003 -0.76585768  0.23308712 -0.53533196]
 [ 1.19361097  1.38571574  1.09755858  1.57782051  1.28966335]
 [-1.11164627 -0.9195415  -1.20769865 -1.01559388 -0.82348911]]


In [52]:
notas = np.array([
    [7.5, 8.0, 6.5, 9.0],
    [5.5, 6.0, 7.0, 5.0],
    [9.0, 8.5, 9.5, 8.0],
    [4.0, 5.5, 6.0, 5.5]
])

In [53]:
media_por_aluno = notas.mean(axis=1)
print("Média por aluno:", media_por_aluno)

Média por aluno: [7.75  5.875 8.75  5.25 ]


In [54]:
aprovados = media_por_aluno >= 6.0
print("Aprovados (True/False):", aprovados)
print("Quantidade de aprovados:", aprovados.sum())

Aprovados (True/False): [ True False  True False]
Quantidade de aprovados: 2


In [55]:
melhor_aluno = media_por_aluno.argmax()
print(f"Melhor aluno: índice {melhor_aluno}, média {media_por_aluno[melhor_aluno]:.2f}")

Melhor aluno: índice 2, média 8.75
